In [1]:
import sklearn.metrics

true = [ 0 ] * 6500 + [ 1 ] * 100 + [ 0 ] * 3400
pred = [ i for i in range(10000) ]
sklearn.metrics.roc_curve(true, pred)

(array([0.00000000e+00, 1.01010101e-04, 3.43434343e-01, 3.43434343e-01,
        1.00000000e+00]),
 array([0., 0., 0., 1., 1.]),
 array([10000,  9999,  6600,  6500,     0]))

In [2]:
import numpy
import sklearn.linear_model

feature = [ 0 ] * 48 + [ 1 ] * 52
target = [ 1 ] * 20 + [ 0 ] * 28 + [ 1 ] * 35 + [ 0 ] * 17

model = sklearn.linear_model.LogisticRegression(penalty = 'none')
model.fit(numpy.array(feature).reshape(-1, 1), numpy.array(target))
model.predict_proba([ [ 1 ] ])

array([[0.32692351, 0.67307649]])

In [3]:
import sklearn.metrics
import sklearn.neighbors
sklearn.neighbors.KNeighborsClassifier(n_neighbors = 1)

import sklearn.model_selection

sklearn.model_selection.GridSearchCV(
    estimator = sklearn.neighbors.KNeighborsClassifier(),
    param_grid = {
        'n_neighbors': [ 1, 2, 3 ]
    },
    scoring = 'accuracy',
    cv = sklearn.model_selection.LeaveOneOut()
).fit(numpy.array([
        [ -1, 1 ],
        [ 1, -1 ],
        [ 1, 1 ],
        [ 0, 0 ]
    ]),
    numpy.array([ 1, 1, 1, -1 ])
).cv_results_

{'mean_fit_time': array([0.00050032, 0.00024986, 0.        ]),
 'std_fit_time': array([0.00050032, 0.00043277, 0.        ]),
 'mean_score_time': array([0.00025022, 0.0004999 , 0.00050014]),
 'std_score_time': array([0.00043339, 0.0004999 , 0.00050014]),
 'param_n_neighbors': masked_array(data=[1, 2, 3],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1}, {'n_neighbors': 2}, {'n_neighbors': 3}],
 'split0_test_score': array([0., 0., 1.]),
 'split1_test_score': array([0., 0., 1.]),
 'split2_test_score': array([0., 0., 1.]),
 'split3_test_score': array([0., 0., 0.]),
 'mean_test_score': array([0.  , 0.  , 0.75]),
 'std_test_score': array([0.       , 0.       , 0.4330127]),
 'rank_test_score': array([2, 2, 1])}

In [4]:
((8/3) * 4) / numpy.sqrt((8/3) ** 2 + 4 ** 2) - (6 / numpy.sqrt(13))

0.5547001962252287

In [5]:
import pandas

df_train = pandas.read_csv("Data_train.csv")
df_test = pandas.read_csv("Data_test.csv")

df_train 

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3  
0         63       67       67  
1         67       69       75  
2         69       90       88  
3         62       64       66  
4         93       90       83  
..       ...      ...      ...  
695       67       73       68  
696        8       24       23  
697       85       75       68  
698       53       45       40  
699       79       79       78  

[700 rows x 8 columns]

In [6]:
df_train[["group"]] = df_train[["group"]].fillna("group F")
df_test[["group"]] = df_test[["group"]].fillna("group F")

In [7]:
df_train.isna().any()

type                  False
group                 False
education             False
meal                  False
preparation course    False
score-1               False
score-2               False
score-3               False
dtype: bool

In [8]:
df_train["Pass"] = (df_train["score-1"] > 50) & (df_train["score-2"] > 50) & (df_train["score-3"] > 50)
df_train

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3   Pass  
0         63       67       67   True  
1         67       69       75   True  
2         69       90       88   True  
3         62       64       66   True  
4         93       90       83   True  
..       ...      ...      ...    ...  
695       67       73       68   True  
696        8       24       23  False  
697       85       75       68   True  
698       53       45       40  False  
699       79       79       78   True  

[700 rows x 9 columns]

In [9]:
df_train[df_train["Pass"] == False]

type    group           education      meal preparation course  \
6        wild  group B    some high school   reduced               none   
11   domestic  group D         high school   reduced               none   
17   domestic  group C    some high school   reduced               none   
19       wild  group B         high school  standard          completed   
20   domestic  group C        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
684  domestic  group B  associate's degree   reduced               none   
685      wild  group B         high school  standard               none   
694  domestic  group E    some high school   reduced               none   
696  domestic  group B         high school   reduced               none   
698      wild  group E  associate's degree  standard               none   

     score-1  score-2  score-3   Pass  
6         48       52       45  False  
11        49       57       52  False  
17        48       56       51  False  
19        60       44       47  False  
20        35       44       43  False  
..       ...      ...      ...    ...  
684       46       61       55  False  
685       57       48       51  False  
694       38       49       45  False  
696        8       24       23  False  
698       53       45       40  False  

[145 rows x 9 columns]

In [10]:
wild = df_train[df_train["type"] == "wild"]
wild

type    group           education      meal preparation course  score-1  \
0    wild  group B    some high school  standard          completed       63   
4    wild  group E        some college   reduced               none       93   
5    wild  group D  associate's degree  standard               none       61   
6    wild  group B    some high school   reduced               none       48   
16   wild  group D    some high school  standard          completed       77   
..    ...      ...                 ...       ...                ...      ...   
693  wild  group E   bachelor's degree   reduced          completed       79   
695  wild  group C    some high school  standard          completed       67   
697  wild  group E        some college  standard          completed       85   
698  wild  group E  associate's degree  standard               none       53   
699  wild  group C        some college  standard          completed       79   

     score-2  score-3   Pass  
0         67       67   True  
4         90       83   True  
5         55       52   True  
6         52       45  False  
16        68       69   True  
..       ...      ...    ...  
693       74       72   True  
695       73       68   True  
697       75       68   True  
698       45       40  False  
699       79       78   True  

[343 rows x 9 columns]

In [11]:
domestic = df_train[df_train["type"] == "domestic"]
domestic

type    group           education      meal preparation course  \
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
7    domestic  group B    some high school  standard               none   
8    domestic  group E  associate's degree   reduced          completed   
..        ...      ...                 ...       ...                ...   
689  domestic  group D     master's degree  standard               none   
690  domestic  group D     master's degree  standard               none   
691  domestic  group D    some high school  standard               none   
694  domestic  group E    some high school   reduced               none   
696  domestic  group B         high school   reduced               none   

     score-1  score-2  score-3   Pass  
1         67       69       75   True  
2         69       90       88   True  
3         62       64       66   True  
7         66       69       68   True  
8         83       86       88   True  
..       ...      ...      ...    ...  
689       87      100      100   True  
690       55       64       70   True  
691       51       63       61   True  
694       38       49       45  False  
696        8       24       23  False  

[357 rows x 9 columns]

In [12]:
p1 = wild[wild["Pass"] == True].shape[0] / wild.shape[0]
p1

0.7813411078717201

In [13]:
p2 = domestic[domestic["Pass"] == True].shape[0] / domestic.shape[0]
p2

0.803921568627451

In [14]:
p2 - p1

0.022580460755730947

In [15]:
non_pass = df_train[df_train["Pass"] == False]
non_pass

type    group           education      meal preparation course  \
6        wild  group B    some high school   reduced               none   
11   domestic  group D         high school   reduced               none   
17   domestic  group C    some high school   reduced               none   
19       wild  group B         high school  standard          completed   
20   domestic  group C        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
684  domestic  group B  associate's degree   reduced               none   
685      wild  group B         high school  standard               none   
694  domestic  group E    some high school   reduced               none   
696  domestic  group B         high school   reduced               none   
698      wild  group E  associate's degree  standard               none   

     score-1  score-2  score-3   Pass  
6         48       52       45  False  
11        49       57       52  False  
17        48       56       51  False  
19        60       44       47  False  
20        35       44       43  False  
..       ...      ...      ...    ...  
684       46       61       55  False  
685       57       48       51  False  
694       38       49       45  False  
696        8       24       23  False  
698       53       45       40  False  

[145 rows x 9 columns]

In [16]:
(non_pass["education"] == "high school").sum()

35

In [17]:
pass_wild = wild[wild["Pass"] == True]
pass_wild

type    group           education      meal preparation course  score-1  \
0    wild  group B    some high school  standard          completed       63   
4    wild  group E        some college   reduced               none       93   
5    wild  group D  associate's degree  standard               none       61   
16   wild  group D    some high school  standard          completed       77   
22   wild  group B   bachelor's degree  standard               none       59   
..    ...      ...                 ...       ...                ...      ...   
692  wild  group D   bachelor's degree  standard          completed       68   
693  wild  group E   bachelor's degree   reduced          completed       79   
695  wild  group C    some high school  standard          completed       67   
697  wild  group E        some college  standard          completed       85   
699  wild  group C        some college  standard          completed       79   

     score-2  score-3  Pass  
0         67       67  True  
4         90       83  True  
5         55       52  True  
16        68       69  True  
22        54       51  True  
..       ...      ...   ...  
692       74       74  True  
693       74       72  True  
695       73       68  True  
697       75       68  True  
699       79       78  True  

[268 rows x 9 columns]

In [18]:
(pass_wild["preparation course"] == "none").sum()

152

In [19]:
df_train["score-1"].median()

66.0

In [20]:
domestic_nocourse = domestic[domestic["preparation course"] == "none"]
domestic_nocourse

type    group          education      meal preparation course  \
1    domestic  group C  bachelor's degree  standard               none   
3    domestic  group B   some high school  standard               none   
7    domestic  group B   some high school  standard               none   
10   domestic  group A        high school  standard               none   
11   domestic  group D        high school   reduced               none   
..        ...      ...                ...       ...                ...   
689  domestic  group D    master's degree  standard               none   
690  domestic  group D    master's degree  standard               none   
691  domestic  group D   some high school  standard               none   
694  domestic  group E   some high school   reduced               none   
696  domestic  group B        high school   reduced               none   

     score-1  score-2  score-3   Pass  
1         67       69       75   True  
3         62       64       66   True  
7         66       69       68   True  
10        55       73       73   True  
11        49       57       52  False  
..       ...      ...      ...    ...  
689       87      100      100   True  
690       55       64       70   True  
691       51       63       61   True  
694       38       49       45  False  
696        8       24       23  False  

[230 rows x 9 columns]

In [21]:
series = domestic_nocourse["score-3"]
series = series.to_numpy()
series

array([ 75,  66,  68,  73,  52,  76,  68,  82,  51,  61,  43,  74,  45,
        72,  51,  57,  62,  64,  82,  51,  88,  80,  43,  52,  59,  77,
        87,  68,  51,  82,  75,  70,  54,  64,  74,  61,  62,  74,  84,
        62,  90,  79,  74,  94,  57,  62,  85,  74,  54,  56,  67,  90,
        70,  77,  62,  47,  70,  77,  72,  70,  56,  61,  33,  74,  80,
        63,  27,  76,  78,  54,  72,  63,  58,  63,  74,  67,  53,  65,
        39,  86,  58,  79,  96,  62,  76,  63,  72,  68,  92,  84,  80,
        59,  63,  83,  71,  57,  86,  68,  80,  65,  59,  79,  73,  82,
        99,  55,  64,  76,  70,  71,  75,  58,  40,  82,  65,  76,  72,
        62,  48,  73,  69, 100,  64,  80,  71,  66,  68,  70,  64, 100,
        71,  80,  88,  70,  61,  54,  82,  10,  70,  79,  67,  74,  61,
        53,  82,  93,  90,  65,  77,  91,  68, 100,  54,  28,  55,  38,
        56,  94,  51,  82,  80,  84,  56,  73,  79,  84,  91,  57,  32,
        70,  54,  67,  92,  75,  65,  53,  79,  63,  66,  67,  8

In [22]:
series.sort()
series

array([ 10,  23,  27,  28,  32,  33,  33,  38,  38,  39,  40,  43,  43,
        43,  43,  43,  45,  45,  47,  48,  50,  50,  51,  51,  51,  51,
        51,  52,  52,  53,  53,  53,  54,  54,  54,  54,  54,  54,  54,
        55,  55,  55,  55,  55,  56,  56,  56,  56,  57,  57,  57,  57,
        57,  58,  58,  58,  58,  59,  59,  59,  60,  61,  61,  61,  61,
        61,  61,  61,  62,  62,  62,  62,  62,  62,  62,  62,  62,  63,
        63,  63,  63,  63,  63,  64,  64,  64,  64,  64,  65,  65,  65,
        65,  65,  66,  66,  66,  67,  67,  67,  67,  67,  67,  68,  68,
        68,  68,  68,  68,  68,  68,  68,  69,  69,  70,  70,  70,  70,
        70,  70,  70,  70,  70,  70,  70,  71,  71,  71,  71,  72,  72,
        72,  72,  72,  73,  73,  73,  73,  73,  73,  74,  74,  74,  74,
        74,  74,  74,  74,  74,  74,  74,  75,  75,  75,  75,  76,  76,
        76,  76,  76,  76,  77,  77,  77,  77,  78,  78,  78,  78,  79,
        79,  79,  79,  79,  79,  80,  80,  80,  80,  80,  80,  8

In [23]:
[ 0, 57.5, 115, 172.5 ]

[0, 57.5, 115, 172.5]

In [24]:
series[57:172]

array([59, 59, 59, 60, 61, 61, 61, 61, 61, 61, 61, 62, 62, 62, 62, 62, 62,
       62, 62, 62, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64, 65, 65, 65,
       65, 65, 66, 66, 66, 67, 67, 67, 67, 67, 67, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 69, 69, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 71,
       71, 71, 71, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73, 73, 74, 74, 74,
       74, 74, 74, 74, 74, 74, 74, 74, 75, 75, 75, 75, 76, 76, 76, 76, 76,
       76, 77, 77, 77, 77, 78, 78, 78, 78, 79, 79, 79, 79], dtype=int64)

In [25]:
115 / series.shape[0]

0.5

In [26]:
series[57:172]

array([59, 59, 59, 60, 61, 61, 61, 61, 61, 61, 61, 62, 62, 62, 62, 62, 62,
       62, 62, 62, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 64, 65, 65, 65,
       65, 65, 66, 66, 66, 67, 67, 67, 67, 67, 67, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 69, 69, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 71,
       71, 71, 71, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73, 73, 74, 74, 74,
       74, 74, 74, 74, 74, 74, 74, 74, 75, 75, 75, 75, 76, 76, 76, 76, 76,
       76, 77, 77, 77, 77, 78, 78, 78, 78, 79, 79, 79, 79], dtype=int64)

In [27]:
79 - 59

20

In [28]:
numpy.quantile(series, 0.25)

59.0

In [29]:
numpy.quantile(series, 0.75)

79.0

In [30]:
(
    (df_train["type"].unique().size - 1) +
    (df_train["group"].unique().size - 1) +
    (df_train["education"].unique().size - 1) +
    (df_train["meal"].unique().size - 1) +
    (df_train["preparation course"].unique().size - 1)
)

13

In [31]:
df_train

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3   Pass  
0         63       67       67   True  
1         67       69       75   True  
2         69       90       88   True  
3         62       64       66   True  
4         93       90       83   True  
..       ...      ...      ...    ...  
695       67       73       68   True  
696        8       24       23  False  
697       85       75       68   True  
698       53       45       40  False  
699       79       79       78   True  

[700 rows x 9 columns]

In [32]:
train_x = df_train[["type", "group", "education", "meal", "preparation course"]]
train_y = df_train[["Pass"]]

test_x = df_train[["type", "group", "education", "meal", "preparation course"]]
test_y = df_train[["Pass"]]

train_x

type    group           education      meal preparation course
0        wild  group B    some high school  standard          completed
1    domestic  group C   bachelor's degree  standard               none
2    domestic  group C        some college  standard          completed
3    domestic  group B    some high school  standard               none
4        wild  group E        some college   reduced               none
..        ...      ...                 ...       ...                ...
695      wild  group C    some high school  standard          completed
696  domestic  group B         high school   reduced               none
697      wild  group E        some college  standard          completed
698      wild  group E  associate's degree  standard               none
699      wild  group C        some college  standard          completed

[700 rows x 5 columns]

In [33]:
import sklearn.preprocessing

encoder = sklearn.preprocessing.OneHotEncoder(sparse=False, drop='first')
train_x = encoder.fit_transform(train_x)
test_x = encoder.transform(test_x)

print(train_x.shape)
print(test_x.shape)

(700, 13)
(700, 13)


In [34]:
import sklearn.model_selection
import sklearn.tree

clf = sklearn.tree.DecisionTreeClassifier(
    splitter='best', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0,
    max_depth = 5,
    criterion = 'entropy',
)

sklearn.model_selection.cross_validate(
    estimator = clf,
    X = train_x,
    y = train_y,
    scoring="roc_auc",
    cv = sklearn.model_selection.KFold(n_splits = 3)
)["test_score"].mean()

0.6695925788481644

In [57]:
clf = sklearn.tree.DecisionTreeClassifier(
    splitter='best', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0,
    criterion = 'entropy'
)

cv = sklearn.model_selection.GridSearchCV(
    estimator = clf,
    param_grid = {
        "max_depth": range(2, 21, 1)
    },
    scoring="roc_auc",
    cv = sklearn.model_selection.KFold(n_splits = 3)
)

res = cv.fit(train_x, train_y)
res.cv_results_["params"][res.cv_results_["mean_test_score"].argmax()]

{'max_depth': 3}

In [42]:
res.cv_results_["mean_test_score"]

array([0.67679191, 0.7176012 , 0.70613242, 0.66891938, 0.64272501,
       0.64437861, 0.62601267, 0.61697426, 0.60677935, 0.6167986 ,
       0.61323133, 0.60882923, 0.61583579, 0.60957535, 0.61621668,
       0.6144404 , 0.61313271, 0.61963036, 0.61015389])

In [200]:
df_train

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3   Pass  
0         63       67       67   True  
1         67       69       75   True  
2         69       90       88   True  
3         62       64       66   True  
4         93       90       83   True  
..       ...      ...      ...    ...  
695       67       73       68   True  
696        8       24       23  False  
697       85       75       68   True  
698       53       45       40  False  
699       79       79       78   True  

[700 rows x 9 columns]

In [204]:
cat_bio = []
for (type, group) in zip(df_train["type"], df_train["group"]):
    cat_bio.append(f'({type}, {group})')
df_train["cat_bio"] = cat_bio
df_train

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3   Pass              cat_bio  
0         63       67       67   True      (wild, group B)  
1         67       69       75   True  (domestic, group C)  
2         69       90       88   True  (domestic, group C)  
3         62       64       66   True  (domestic, group B)  
4         93       90       83   True      (wild, group E)  
..       ...      ...      ...    ...                  ...  
695       67       73       68   True      (wild, group C)  
696        8       24       23  False  (domestic, group B)  
697       85       75       68   True      (wild, group E)  
698       53       45       40  False      (wild, group E)  
699       79       79       78   True      (wild, group C)  

[700 rows x 10 columns]

In [217]:
train_x_new = df_train[['cat_bio', 'education', 'meal', 'preparation course']]
train_y_new = df_train["Pass"]

test_x_new = df_train[['cat_bio', 'education', 'meal', 'preparation course']]
test_y = df_train["Pass"]

train_x

cat_bio           education      meal preparation course
0        (wild, group B)    some high school  standard          completed
1    (domestic, group C)   bachelor's degree  standard               none
2    (domestic, group C)        some college  standard          completed
3    (domestic, group B)    some high school  standard               none
4        (wild, group E)        some college   reduced               none
..                   ...                 ...       ...                ...
695      (wild, group C)    some high school  standard          completed
696  (domestic, group B)         high school   reduced               none
697      (wild, group E)        some college  standard          completed
698      (wild, group E)  associate's degree  standard               none
699      (wild, group C)        some college  standard          completed

[700 rows x 4 columns]

In [218]:
import sklearn.preprocessing

encoder = sklearn.preprocessing.OneHotEncoder(sparse=False, drop='first')
train_x = encoder.fit_transform(train_x)
test_x = encoder.transform(test_x)

print(train_x.shape)
print(test_x.shape)

(700, 18)
(700, 18)


In [219]:
import sklearn.model_selection
import sklearn.tree

clf = sklearn.tree.DecisionTreeClassifier(
    splitter='best', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0,
    max_depth = 5,
    criterion = 'entropy',
)

sklearn.model_selection.cross_validate(
    estimator = clf,
    X = train_x,
    y = train_y,
    scoring="roc_auc",
    cv = sklearn.model_selection.KFold(n_splits = 3)
)["test_score"].mean()

0.681442451383392

In [223]:
train_y.to_numpy()

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,

In [235]:
import sklearn.metrics

clf2 = clf.fit(train_x, train_y.to_numpy())
sklearn.metrics.roc_auc_score(train_y.to_numpy(), clf2.predict_proba(train_x)[:, 1])

0.7899534016775396

In [236]:
df_train

type    group           education      meal preparation course  \
0        wild  group B    some high school  standard          completed   
1    domestic  group C   bachelor's degree  standard               none   
2    domestic  group C        some college  standard          completed   
3    domestic  group B    some high school  standard               none   
4        wild  group E        some college   reduced               none   
..        ...      ...                 ...       ...                ...   
695      wild  group C    some high school  standard          completed   
696  domestic  group B         high school   reduced               none   
697      wild  group E        some college  standard          completed   
698      wild  group E  associate's degree  standard               none   
699      wild  group C        some college  standard          completed   

     score-1  score-2  score-3   Pass              cat_bio  
0         63       67       67   True      (wild, group B)  
1         67       69       75   True  (domestic, group C)  
2         69       90       88   True  (domestic, group C)  
3         62       64       66   True  (domestic, group B)  
4         93       90       83   True      (wild, group E)  
..       ...      ...      ...    ...                  ...  
695       67       73       68   True      (wild, group C)  
696        8       24       23  False  (domestic, group B)  
697       85       75       68   True      (wild, group E)  
698       53       45       40  False      (wild, group E)  
699       79       79       78   True      (wild, group C)  

[700 rows x 10 columns]

In [239]:
df_test
cat_bio = []
for (type, group) in zip(df_test["type"], df_test["group"]):
    cat_bio.append(f'({type}, {group})')
df_test["cat_bio"] = cat_bio
df_test

type    group           education      meal preparation course  \
0        wild  group D        some college  standard               none   
1        wild  group C     master's degree   reduced          completed   
2        wild  group B        some college   reduced          completed   
3        wild  group A  associate's degree   reduced               none   
4    domestic  group B        some college  standard          completed   
..        ...      ...                 ...       ...                ...   
295  domestic  group B        some college   reduced               none   
296  domestic  group C     master's degree  standard               none   
297      wild  group D         high school   reduced               none   
298  domestic  group C    some high school   reduced               none   
299  domestic  group D        some college   reduced               none   

                 cat_bio  
0        (wild, group D)  
1        (wild, group C)  
2        (wild, group B)  
3        (wild, group A)  
4    (domestic, group B)  
..                   ...  
295  (domestic, group B)  
296  (domestic, group C)  
297      (wild, group D)  
298  (domestic, group C)  
299  (domestic, group D)  

[300 rows x 6 columns]

In [254]:
tr_x1 = df_train[['cat_bio', 'education', 'meal', 'preparation course']]
tr_x2 = df_train[['type', "group", 'education', 'meal', 'preparation course']]
tr_y = df_train["Pass"].to_numpy()

te_x1 = df_test[['cat_bio', 'education', 'meal', 'preparation course']]
te_x2 = df_test[['type', "group", 'education', 'meal', 'preparation course']]

print(tr_x1.shape)
print(tr_x2.shape)
print(tr_y.shape)
print(te_x1.shape)
print(te_x2.shape)

(700, 4)
(700, 5)
(700,)
(300, 4)
(300, 5)


In [255]:
import sklearn.preprocessing

encoder = sklearn.preprocessing.OneHotEncoder(sparse=False, drop='first')
tr_x1 = encoder.fit_transform(tr_x1)
te_x1 = encoder.transform(te_x1)

tr_x2 = encoder.fit_transform(tr_x2)
te_x2 = encoder.transform(te_x2)

print(tr_x1.shape)
print(tr_x2.shape)
print(tr_y.shape)
print(te_x1.shape)
print(te_x2.shape)

(700, 18)
(700, 13)
(700,)
(300, 18)
(300, 13)


In [267]:
import sklearn.linear_model
import sklearn.model_selection
import sklearn.ensemble

clf = sklearn.linear_model.LogisticRegression(
)

sklearn.model_selection.cross_validate(
    estimator = clf,
    X = tr_x1,
    y = tr_y,
    scoring="roc_auc",
    cv = sklearn.model_selection.KFold(n_splits = 3)
)["test_score"].mean()

0.7166709507492476

In [379]:
import sklearn.metrics
import sklearn.model_selection

numpy.random.seed(42)

train_x, test_x, train_y, test_y = sklearn.model_selection.train_test_split(tr_x1, tr_y, test_size = 0.25)
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

import torch
import torch.utils.data

torch.manual_seed(42)

train_ds = torch.utils.data.TensorDataset(torch.tensor(train_x, dtype=torch.float),
                                          torch.tensor(train_y, dtype=torch.float).reshape(-1, 1))
test_ds = torch.utils.data.TensorDataset(torch.tensor(test_x, dtype=torch.float),
                                         torch.tensor(test_y, dtype=torch.float).reshape(-1, 1))

train_dl = torch.utils.data.DataLoader(train_ds, batch_size = 64, shuffle = True)
test_dl = torch.utils.data.DataLoader(test_ds, batch_size = len(test_ds))

model = torch.nn.Sequential(
    torch.nn.Linear(train_x.shape[1], 8), torch.nn.GELU(),
    torch.nn.Dropout(0.1), torch.nn.Linear(8, 1),
)

optimizer = torch.optim.AdamW(
    params = model.parameters(),
    # lr = 1e-5
)

for _ in range(100):
    for batch_x, batch_y in train_dl:
        model.train()
        pred = model(batch_x)
        loss = torch.nn.functional.binary_cross_entropy_with_logits(pred, batch_y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    with torch.no_grad():
        model.eval()
        batch_x, batch_y = next(iter(test_dl))
        pred = model(batch_x)
        # print(torch.nn.functional.cross_entropy(pred, batch_y))
        if sklearn.metrics.roc_auc_score(batch_y, pred) > 0.75:
            print(_, sklearn.metrics.roc_auc_score(batch_y, pred))


final_x = torch.tensor(te_x1, dtype = torch.float)
pred = model(final_x)
numpy.savetxt("result.txt", pred.detach().numpy())

(525, 18)
(525,)
(175, 18)
(175,)
79 0.751734906315059
80 0.7524288688410825
81 0.7539902845246357
82 0.7562456627342123
83 0.7571131158917419
84 0.756939625260236
85 0.7578070784177655
86 0.7574600971547536
87 0.7572866065232478
88 0.7564191533657182
89 0.7564191533657182
90 0.7581540596807773
91 0.7600624566273422
92 0.7605829285218598
93 0.7605829285218598
94 0.7607564191533658
95 0.7619708535739069
96 0.7621443442054129
97 0.7614503816793894
98 0.7611034004163776
99 0.7602359472588481
